---
- hosts: localhost
  user: ubuntu
  tasks:
  - name: update homebrew
    homebrew:
      update_homebrew: yes
      upgrade_all: yes
    when: ansible_os_family == "Darwin"
  - name: Tap casks
    homebrew_tap: name={{item}} state=present
    with_items:
      - caskroom/cask
      - osx-cross/avr
      - PX4/homebrew-px4
    when: ansible_os_family == "Darwin"
  - name: install cask apps
    homebrew_cask: name={{item}} state=present
    with_items:
      - keycastr
      - slack
      - virtualbox
      - dropbox
      - google-chrome
    when: ansible_os_family == "Darwin"
  - name: Install core packages
    package: name={{item}} state=installed
    with_items:
      - git
      - vim
      - zsh
      - wget
      - jq
      - rbenv
      - tmux
      - nmap
      - make
      - gcc
      - python3
      - avr-gcc
      - dfu-programmer
      - gcc-arm-none-eabi
      - nvm
      - cmake
      - rpm
  - name: Install OSX specific packages
    package: name={{item}} state=installed
    with_items:
      - macvim
      - cloudfoundry/tap/cf-cli
      - terraform
      - packer
      - docker-compose
    when: ansible_os_family == "Darwin"
  - name: Add Ubuntu keys
    apt_key:
      url: https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key
      state: present
      validate_certs: no
    become: yes
    when: ansible_os_family == "Debian"
  - name: Add CF-CLI repo
    apt_repository:
      repo: deb http://packages.cloudfoundry.org/debian stable main
      state: present
      filename: 'cloudfoundry-cli'
    become: yes
    when: ansible_os_family == "Debian"
  - name: Install Debian/Ubuntu specific packages
    package: name={{item}} state=installed
    with_items:
      - cf-cli
    become: yes
    when: ansible_os_family == "Debian"
  - name: Install oh-my-zsh
    git:
      repo: https://github.com/nctiggy/oh-my-zsh.git
      dest: $HOME/.oh-my-zsh
  - name: Clone dotfiles
    git:
      repo: https://github.com/nctiggy/dotfiles.git
      dest: $HOME/.myconf
      bare: yes
  - name: Checkout the dotfiles
    command: /usr/bin/git --git-dir=$HOME/.myconf/ --work-tree=$HOME checkout
  - name: Turn of untracked files
    command: /usr/bin/git --git-dir=$HOME/.myconf/ --work-tree=$HOME config status.showUntrackedFiles no
  - name: Get Dracula ZSH theme
    git:
      repo:  https://github.com/dracula/zsh.git
      dest: $HOME/.dracula-zsh
  - name: Update all ZSH submodules
    command: git submodule update --recursive --remote
    args:
      chdir: $HOME/.oh-my-zsh
  - name: clone my vim files
    git:
      repo: https://github.com/nctiggy/vim-repo.git
      dest: $HOME/.vim
  - name: Update all vim submodules
    command: git submodule update --recursive --remote
    args:
      chdir: $HOME/.vim
  - name: create Sites directory
    file: path=$HOME/Sites state=directory
  - name: clone dracula terminal theme to Sites dir
    git:
      repo: https://github.com/dracula/terminal.app.git
      dest: $HOME/Sites/dracula-terminal-theme
